#!/bin/sh

set -e

if [ "$1" = "configure" ]
then
    if ! getent passwd keystone > /dev/null 2>&1
    then
        adduser --system --home /var/lib/keystone --no-create-home --shell /bin/bash keystone
    fi
    chown keystone -R /var/lib/keystone /var/log/keystone
    if ! grep sql_connection /etc/keystone/keystone.conf | grep -qv "sql_connection = sqlite:////var/lib/keystone/keystone.sqlite"
    then
        su -c 'keystone-manage db_sync' keystone
    fi
fi

#DEBHELPER#
